apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-n6ue
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-99-tenant/load-app-406fe753-9e14-41ea-8b70-e2542f9352b2/devfile-sample-n6ue@sha256:21b33c6dc32d1e820a26fd05eff2368ce70f826d17e986b5b8dc900897043e79
        name: my-nodejs
        resources: {}
status: {}
